version: "3.6"
services:
  db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"