version: "3.6"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"


networks:
  default:
    driver: bridge