version: "3.6"
services:
  db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: "shortcuts"
      POSTGRES_USER: "tbp"
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"